name: appli_lite
description: Appli, uma forma simplificada de acompanhamento de obra.
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  firebase_auth: ^4.2.9
  firebase_core: ^2.7.0
  firebase_database:
  flutter:
    sdk: flutter
  top_snackbar_flutter: ^3.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

fonts:
  - family: open-sans
    fonts:
      - asset: assets/fonts/OpenSans-VariableFont_wdth,wght.ttf
        style: normal